// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/owner_model.dart';
import 'models/task_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4131110784150435634),
      name: 'OwnerModel',
      lastPropertyId: const obx_int.IdUid(2, 3261676730357205871),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6950657578035032093),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3261676730357205871),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 7156124954724861950),
      name: 'TaskModel',
      lastPropertyId: const obx_int.IdUid(5, 5266528660543603968),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7597896564268734351),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1265453502292372153),
            name: 'text',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 323439598975279873),
            name: 'isFinished',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2313169236032150573),
            name: 'dateTime',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5266528660543603968),
            name: 'ownerId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 4258185765294313609),
            relationTarget: 'OwnerModel')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 7156124954724861950),
      lastIndexId: const obx_int.IdUid(1, 4258185765294313609),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    OwnerModel: obx_int.EntityDefinition<OwnerModel>(
        model: _entities[0],
        toOneRelations: (OwnerModel object) => [],
        toManyRelations: (OwnerModel object) => {},
        getId: (OwnerModel object) => object.id,
        setId: (OwnerModel object, int id) {
          object.id = id;
        },
        objectToFB: (OwnerModel object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = OwnerModel(nameParam, id: idParam);

          return object;
        }),
    TaskModel: obx_int.EntityDefinition<TaskModel>(
        model: _entities[1],
        toOneRelations: (TaskModel object) => [object.owner],
        toManyRelations: (TaskModel object) => {},
        getId: (TaskModel object) => object.id,
        setId: (TaskModel object, int id) {
          object.id = id;
        },
        objectToFB: (TaskModel object, fb.Builder fbb) {
          final textOffset = fbb.writeString(object.text);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, textOffset);
          fbb.addBool(2, object.isFinished);
          fbb.addInt64(3, object.dateTime?.millisecondsSinceEpoch);
          fbb.addInt64(4, object.owner.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dateTimeValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final textParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final isFinishedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final dateTimeParam = dateTimeValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dateTimeValue);
          final object = TaskModel(textParam,
              id: idParam,
              isFinished: isFinishedParam,
              dateTime: dateTimeParam);
          object.owner.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.owner.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [OwnerModel] entity fields to define ObjectBox queries.
class OwnerModel_ {
  /// See [OwnerModel.id].
  static final id =
      obx.QueryIntegerProperty<OwnerModel>(_entities[0].properties[0]);

  /// See [OwnerModel.name].
  static final name =
      obx.QueryStringProperty<OwnerModel>(_entities[0].properties[1]);
}

/// [TaskModel] entity fields to define ObjectBox queries.
class TaskModel_ {
  /// See [TaskModel.id].
  static final id =
      obx.QueryIntegerProperty<TaskModel>(_entities[1].properties[0]);

  /// See [TaskModel.text].
  static final text =
      obx.QueryStringProperty<TaskModel>(_entities[1].properties[1]);

  /// See [TaskModel.isFinished].
  static final isFinished =
      obx.QueryBooleanProperty<TaskModel>(_entities[1].properties[2]);

  /// See [TaskModel.dateTime].
  static final dateTime =
      obx.QueryDateProperty<TaskModel>(_entities[1].properties[3]);

  /// See [TaskModel.owner].
  static final owner =
      obx.QueryRelationToOne<TaskModel, OwnerModel>(_entities[1].properties[4]);
}
